#ifndef __STARFISHNET_H__
#define __STARFISHNET_H__

#include "net/netstack.h"

#define STARFISHNET_DEFAULT_TX_RETRY_LIMIT 5
#define STARFISHNET_DEFAULT_TX_RETRY_TIMEOUT 2500

#ifndef STARFISHNET_TX_RETRY_LIMIT
#define STARFISHNET_TX_RETRY_LIMIT STARFISHNET_DEFAULT_TX_RETRY_LIMIT
#endif /* STARFISHNET_TX_RETRY_LIMIT */

#ifndef STARFISHNET_TX_RETRY_TIMEOUT
#define STARFISHNET_TX_RETRY_TIMEOUT STARFISHNET_DEFAULT_TX_RETRY_TIMEOUT
#endif /* STARFISHNET_TX_RETRY_TIMEOUT */

extern const struct network_driver starfishnet_driver;

#endif //__STARFISHNET_H__
